language: node_js
node_js:
- 8.11.4
branches:
  only:
  - production
cache:
  yarn: true
  directories: "$HOME/google-cloud-sdk"

before_install:
  - openssl aes-256-cbc -K $encrypted_3432a4eadc06_key -iv $encrypted_3432a4eadc06_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

install:
  - yarn

deploy:
  provider: script
  skip_cleanup: true
  script: npm run publish
  on: production